http {
    server_tokens on;

    server {
        listen 443 ssl;
        server_name example.com;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!MD5:RC4;

        client_max_body_size 0;

        location / {
            autoindex on;
            root /var/www/html;
        }
    }
}
